package registries

// RFC5545 section  https://datatracker.ietf.org/doc/html/rfc5545#section-8.3.2

type Properties string

const (
	CALSCALE        Properties = "CALSCALE"
	METHOD          Properties = "METHOD"
	PRODID          Properties = "PRODID"
	VERSION         Properties = "VERSION"
	ATTACH          Properties = "ATTACH"
	CATEGORIES      Properties = "CATEGORIES"
	CLASS           Properties = "CLASS"
	COMMENT         Properties = "COMMENT"
	DESCRIPTION     Properties = "DESCRIPTION"
	GEO             Properties = "GEO"
	LOCATION        Properties = "LOCATION"
	PERCENTCOMPLETE Properties = "PERCENT-COMPLETE"
	PRIORITY        Properties = "PRIORITY"
	RESOURCES       Properties = "RESOURCES"
	STATUS          Properties = "STATUS"
	SUMMARY         Properties = "SUMMARY"
	COMPLETED_PROP  Properties = "COMPLETED"
	DTEND           Properties = "DTEND"
	DUE             Properties = "DUE"
	DTSTART         Properties = "DTSTART"
	DURATION_PROP   Properties = "DURATION"
	FREEBUSY        Properties = "FREEBUSY"
	TRANSP          Properties = "TRANSP"
	PROP_TZID       Properties = "TZID"
	TZNAME          Properties = "TZNAME"
	TZOFFSETFROM    Properties = "TZOFFSETFROM"
	TZOFFSETTO      Properties = "TZOFFSETTO"
	ATTENDEE        Properties = "ATTENDEE"
	TZURL           Properties = "TZURL"
	CONTACT         Properties = "CONTACT"
	ORGANIZER       Properties = "ORGANIZER"
	RELATEDTO       Properties = "RELATED-TO"
	RECURRENCEID    Properties = "RECURRENCE-ID"
	URL             Properties = "URL"
	UID             Properties = "UID"
	EXDATE          Properties = "EXDATE"
	EXRULE          Properties = "EXRULE"
	RDATE           Properties = "RDATE"
	RRULE           Properties = "RRULE"
	ACTION          Properties = "ACTION"
	REPEAT          Properties = "REPEAT"
	CREATED         Properties = "CREATED"
	TRIGGER         Properties = "TRIGGER"
	DTSTAMP         Properties = "DTSTAMP"
	LASTMODIFIED    Properties = "LAST-MODIFIED"
	SEQUENCE        Properties = "SEQUENCE"
	REQUESTSTATUS   Properties = "REQUEST-STATUS"
	BEGIN           Properties = "BEGIN"
	END             Properties = "END"
)
